### ISSUE TITLE
[Request] Please add debug logging to construct command

### ISSUE THREAD

**Issue by mike-carey** [cloudfoundry-incubator/stembuild#11]
The `debug` flag is available but is only used in the `package` functionality.  It would be nice to have `debug` information when running the `construct` functionality as well.

**Comment by kartiklunkad26** [comment]
@mike-carey thank you for reaching out. Because construct happens asynchronously, adding debug functionality is a significant feature. We are definitely investigating on how we can provide more logs from the construct command, but debug might be a hard feature to add. 

Could you give us more insight as to the need for the debug flag during construct?

**Comment by mike-carey** [comment]
I actually think the logging might be fine.  We were having issues figuring out where we were in the steps while it was failing.  I think the issue is actually that `govc`'s error messages are not clear enough.  I will close this issue.
